// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIxL3S3QykUqt48nZajXF7UWCfEPYYUY',
    appId: '1:180675252341:web:f140de640283670d31e83c',
    messagingSenderId: '180675252341',
    projectId: 'vinclyapp',
    authDomain: 'vinclyapp.firebaseapp.com',
    storageBucket: 'vinclyapp.firebasestorage.app',
    measurementId: 'G-8NWE9N1GLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_i8gJTxoGU29_8NoPsmoOVZ7L6Fr3O9Y',
    appId: '1:180675252341:android:ee399e56a7e5972131e83c',
    messagingSenderId: '180675252341',
    projectId: 'vinclyapp',
    storageBucket: 'vinclyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuHzwBt3wNOxGylK_nvusxNVHEF5c-zeo',
    appId: '1:180675252341:ios:923b5b3d4a310c6431e83c',
    messagingSenderId: '180675252341',
    projectId: 'vinclyapp',
    storageBucket: 'vinclyapp.firebasestorage.app',
    iosBundleId: 'com.example.vincly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuHzwBt3wNOxGylK_nvusxNVHEF5c-zeo',
    appId: '1:180675252341:ios:923b5b3d4a310c6431e83c',
    messagingSenderId: '180675252341',
    projectId: 'vinclyapp',
    storageBucket: 'vinclyapp.firebasestorage.app',
    iosBundleId: 'com.example.vincly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxIxL3S3QykUqt48nZajXF7UWCfEPYYUY',
    appId: '1:180675252341:web:6372f1f2bb27c70031e83c',
    messagingSenderId: '180675252341',
    projectId: 'vinclyapp',
    authDomain: 'vinclyapp.firebaseapp.com',
    storageBucket: 'vinclyapp.firebasestorage.app',
    measurementId: 'G-JTQFBTL5LX',
  );
}
